---
- Argh
- Aww snap
- Boo
- Boo-hoo
- Bummer
- Crickey
- Crud
- Dagnabit
- Dang
- Darn
- Drat
- Dâ€™oh
- Fiddlesticks
- Geez
- Golly
- Heavens
- Jeepers
- Oh snap
- Oops
- Ouch
- Phooey
- Rats
- Shoot
- Shucks
- Snap
- Uh oh
- Welp
- Whoops
- Whoopsie
- Yikes
- Yowza
- Zoinks